function extractNumbers (text) {
  let result = '';
  for (let element of text) {
    if(!isNaN(parseInt(element))){
      result+=parseInt(element);
    }
  }
  return result;
}

// 1. Assign by hand same value to 3 variables in binary, octal and hexadecimal format.
let var1 = parseInt('100', 2);
let var2 = parseInt('100', 8);
let var3 = parseInt('100', 16);

console.log(var1, var2, var3);

// 2. Implement function `extractNumbers` which will leave only numbers in passed string.

console.log(extractNumbers('tEst12345 ^& 6test'));

// 3. Declare a variable with decimal value and convert to binary, octal and hexadecimal.

let number = 200;

let binary  = number.toString(2);
let octal = number.toString(8);
let hexadecimal = number.toString(16);

console.log(binary, octal, hexadecimal);

// 4. use `Math.random` to generate random value from `0` to `100`.

let randomV = Math.random() * 100;
console.log(randomV);

// Additional

// 1. Make function which will take a array with numbers as a parameter and
//    calculate average number and round to hundredths.

function findAvg(input){
  let sum = 0;

  for (value in input){
    sum +=input[value];
  }

  let avg = (Math.round((sum/input.length)/100))*100;

  return(avg);
}

// 2. Generate array to pass to function above with values, and length generated by Math.random.

function generateArray(minRange, maxRange, length){
  let array = {length};
  for (i=0; i<length; i++){
    array[i] = Math.round((Math.random() * (maxRange- minRange)) + minRange);
  }
  console.log(array);
  return array;
}

console.log(findAvg(generateArray(15, 555, 10)));